import OrderDetail from "@/components/pages/profile/order/detail/order-detail";
import { Suspense } from "react";

export const metadata = {
	title: `${process.env.WEBSITE_NAME} - Hồ sơ - Chi tiết đơn hàng`,
	description: "Generated by create next app"
};

export default function Page() {
    return (
        <Suspense fallback={"Loading . . ."}>
            <OrderDetail />
        </Suspense>
    )
}
