export const metadata = {
	title: `${process.env.WEBSITE_NAME} - Phiếu giảm giá`,
	description: "Generated by create next app",
};

export default async function Page() {
    return (
        <div>
            page
        </div>
    )
}
