import { Suspense } from "react";

import MainLoading from "@/components/customs/main-loading";
import BookAddress from "@/components/pages/profile/book-address/book-address";

export const metadata = {
	title: `${process.env.WEBSITE_NAME} - Hồ sơ - Sổ địa chỉ`,
	description: "Generated by create next app"
};

export default function Page() {
    return (
        <Suspense fallback={<MainLoading />}>
            <BookAddress />
        </Suspense>
    )
}
