import ProductsList from "@/components/pages/products/products-list";

export const metadata = {
	title: `${process.env.WEBSITE_NAME} - Sản phẩm`,
	description: "Generated by create next app",
};

export default function Page() {
    return (
        <ProductsList />
    )
}