export async function generateMetadata() {
    // fetch dữ liệu
  
    return {
        title: `${process.env.WEBSITE_NAME} - Tên sản phẩm`,
        description: "Generated by create next app",
    };
}

export default function Page() {
    return (
        <div>page</div>
    )
}