import ProductsListSearch from "@/components/pages/products/search/products-list-search";

export const metadata = {
	title: `${process.env.WEBSITE_NAME} - Sản phẩm`,
	description: "Generated by create next app",
};

export default function Page() {
    return (
        <ProductsListSearch />
    )
}
