import { Suspense } from "react";

import ProductsListSearch from "@/components/pages/products/search/products-list-search";
import ProductsListSearchLoading from "@/components/pages/products/search/products-list-search-loading";

export const metadata = {
	title: `${process.env.WEBSITE_NAME} - Sản phẩm`,
	description: "Generated by create next app"
};

export default function Page() {
    return (
        <Suspense fallback={<ProductsListSearchLoading />}>
            <ProductsListSearch />
        </Suspense>
    )
}