export const metadata = {
	title: `${process.env.WEBSITE_NAME} - Hồ sơ - Đơn hàng`,
	description: "Generated by create next app"
};

import Order from "@/components/pages/profile/order/order";
import { Suspense } from "react";

export default function Page({ searchParams }) {
    return (
        <Suspense fallback={"Loading . . ."}>
            <Order />
        </Suspense>
    )
}
