import Order from "@/components/pages/profile/order/order";

export const metadata = {
	title: `${process.env.WEBSITE_NAME} - Hồ sơ - Đơn hàng`,
	description: "Generated by create next app"
};

export default function Page({ searchParams }) {
    return (
        <Order searchParams={searchParams} />
    )
}
