import { Suspense } from "react";
import ProductDetail from "@/components/pages/products/detail/product-detail";
import ProductDetailLoading from "@/components/pages/products/detail/product-detail-loading";

export async function generateMetadata() {
    // fetch dữ liệu
    return {
        title: `${process.env.WEBSITE_NAME} - Tên sản phẩm`,
        description: "Generated by create next app",
    };
}

export default function Page({ params }) {
    return (
        <Suspense fallback={<ProductDetailLoading />}>
            <ProductDetail params={params} />
        </Suspense>
    )
}