import UserLayout from "@/components/layouts/user/user-layout";

export const metadata = {
	title: `${process.env.WEBSITE_NAME} - Trang chủ`,
	description: "Generated by create next app",
};

export default function Layout({ children }) {
    return (
        <UserLayout isOverflow={true}>
            {children}
        </UserLayout>
    )
}
