import { Suspense } from "react";
import Cart from "@/components/pages/cart/cart";

export const metadata = {
	title: `${process.env.WEBSITE_NAME} - Giỏ hàng`,
	description: "Generated by create next app",
};

export default function Page() {
    return (
        <Suspense fallback={"Đang tải . . ."}>
            <Cart />
        </Suspense>
    )
}
