import { Suspense } from "react";
import ProfileCoupon from "@/components/pages/profile/coupon/profile-coupon";
import MainLoading from "@/components/customs/main-loading";

export const metadata = {
	title: `${process.env.WEBSITE_NAME} - Hồ sơ - Phiếu giảm giá`,
	description: "Generated by create next app"
};

export default function Page() {
    return (
        <Suspense fallback={<MainLoading />}>
            <ProfileCoupon />
        </Suspense>
    )
}
