import AdminLayout from "@/components/layouts/admin/admin-layout";

export const metadata = {
	title: `${process.env.WEBSITE_NAME} - Quản trị`,
	description: "Generated by create next app",
};

export default function Layout({ children }) {
    return (
        <AdminLayout>
            {children}
        </AdminLayout>
    )
}
