export const metadata = {
	title: `${process.env.WEBSITE_NAME} - Giới thiệu`,
	description: "Generated by create next app",
};

export default function Page() {
    return (
        <div className="pt-[100px]">
            page
        </div>
    )
}
