export const metadata = {
	title: `${process.env.WEBSITE_NAME} - Liên hệ`,
	description: "Generated by create next app",
};

export default function Page() {
    return (
        <div>page</div>
    )
}
