import UserLayout from '@/components/pages/layouts/user/user-layout'

export const metadata = {
	title: `${process.env.WEBSITE_NAME} - Trang chủ`,
	description: "Generated by create next app",
};

export default function Layout({ children }) {
    return (
        <UserLayout>
            {children}
        </UserLayout>
    )
}
