import Home from "@/components/pages/home/home";

export const metadata = {
	title: `${process.env.WEBSITE_NAME} - Trang chủ`,
	description: "Generated by create next app",
};

export default function Page() {
    return (
        <Home />
    )
}